[supabase]
url = "https://kdtyktsjsltqrtwdapga.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkdHlrdHNqc2x0cXJ0d2RhcGdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NzA2MTYsImV4cCI6MjA2NDI0NjYxNn0.IaekJbY19mOoK9dUlgX2Or3H3Z4R0PxAQ86JpLpMnD8"